version: '3.8'

services:
  nginx:
    image: custom-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: my-php-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-net
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=appdb

  db:
    image: mysql:8.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

networks:
  app-net:
    driver: overlay

volumes:
  db_data: